// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiqqcTuGRKlx1hKKm7DLBGwuad69woZp0',
    appId: '1:81469112169:web:16894fa2b2bfadf1ccc7f8',
    messagingSenderId: '81469112169',
    projectId: 'campusease-feeb5',
    authDomain: 'campusease-feeb5.firebaseapp.com',
    storageBucket: 'campusease-feeb5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVjtqtMZeJLICpCUwwBgm4XlWgvvlVYH4',
    appId: '1:81469112169:android:fd8210ea90771021ccc7f8',
    messagingSenderId: '81469112169',
    projectId: 'campusease-feeb5',
    storageBucket: 'campusease-feeb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA10Yxnyb5ewtGuRGMbBVqjwMQTHPCq4Sw',
    appId: '1:81469112169:ios:84b816ee989fb957ccc7f8',
    messagingSenderId: '81469112169',
    projectId: 'campusease-feeb5',
    storageBucket: 'campusease-feeb5.firebasestorage.app',
    iosBundleId: 'com.example.campusease',
  );
}
